env: 
  es6: true
  node: true
extends:
    - airbnb-base
    - plugin:@typescript-eslint/recommended
    - plugin:prettier/recommended
    - plugin:import/recommended
    - plugin:import/typescript
    - next/core-web-vitals
    - next
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 14
    # sourceType: module
    # project: ./tsconfig.json
plugins:
    - '@typescript-eslint'
rules:
    no-console: 'off'
    import/extensions: 'never'
